const reviews = [
  {
    id: '1',
    content: 'Lovely campground!',
    view_score: '4',
    safety_score: '5',
    cost__score: '4',
    clean_score: '4',
    convenience_score: '5',
    user_id: '3',
    camp_id: '2',
  },
  {
    id: '2',
    content: 'Disappointing experience.',
    view_score: '2',
    safety_score: '3',
    cost__score: '2',
    clean_score: '2',
    convenience_score: '3',
    user_id: '6',
    camp_id: '9',
  },
  {
    id: '3',
    content: 'Highly recommended!',
    view_score: '3',
    safety_score: '1',
    cost__score: '4',
    clean_score: '2',
    convenience_score: '5',
    user_id: '9',
    camp_id: '12',
  },
  {
    id: '4',
    content: 'Great value for money.',
    view_score: '2',
    safety_score: '5',
    cost__score: '2',
    clean_score: '1',
    convenience_score: '4',
    user_id: '11',
    camp_id: '16',
  },
  {
    id: '5',
    content: 'Family-friendly campground!',
    view_score: '4',
    safety_score: '5',
    cost__score: '2',
    clean_score: '5',
    convenience_score: '5',
    user_id: '4',
    camp_id: '6',
  },
  {
    id: '6',
    content: 'Good location.',
    view_score: '4',
    safety_score: '5',
    cost__score: '2',
    clean_score: '1',
    convenience_score: '4',
    user_id: '5',
    camp_id: '8',
  },
];

module.exports = {
  reviews,
};
